version: "3.6"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    command: redis-server





volumes:
  redis_volume:
    driver: "local"